run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
    - gocritic
    - gofmt
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
